FROM python:3.12-slim

WORKDIR /work
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend/migrations ./backend/migrations
COPY scripts ./scripts

ENTRYPOINT ["python"]
