-- Generated from the verified SQLite source and reviewed as migration 001.
-- Existing textual date and JSON columns keep their wire semantics.
CREATE TABLE tempo_schema_migrations (version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
-- background_activity
CREATE TABLE background_activity (source TEXT NOT NULL, work_id TEXT NOT NULL, generation_key TEXT, paused BIGINT NOT NULL DEFAULT 0, promoted BIGINT NOT NULL DEFAULT 0, phase TEXT, completed_units BIGINT, total_units BIGINT, updated_at TEXT NOT NULL, PRIMARY KEY (source, work_id));
-- background_tasks
CREATE TABLE background_tasks (id TEXT PRIMARY KEY, kind TEXT NOT NULL, deduplication_key TEXT NOT NULL, generation BIGINT NOT NULL DEFAULT 1, priority BIGINT NOT NULL DEFAULT 100, state TEXT NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'leased', 'retrying', 'complete', 'failed', 'superseded')), phase TEXT NOT NULL DEFAULT 'queued', payload_version BIGINT NOT NULL DEFAULT 1, payload_json TEXT NOT NULL DEFAULT '{}', attempt_count BIGINT NOT NULL DEFAULT 0, max_attempts BIGINT NOT NULL DEFAULT 5, next_attempt_at TEXT NOT NULL, lease_token TEXT, lease_expires_at TEXT, last_error TEXT, created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT, updated_at TEXT NOT NULL, UNIQUE (kind, deduplication_key));
-- card_revisions
CREATE TABLE card_revisions (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, card_id TEXT NOT NULL, revision BIGINT NOT NULL, start_fen TEXT NOT NULL, moves_json TEXT NOT NULL, history_mode TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE (card_id, revision));
-- daily_chess_insights
CREATE TABLE daily_chess_insights (id TEXT PRIMARY KEY, local_day TEXT NOT NULL, kind TEXT NOT NULL, evidence_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- daily_chess_snapshots
CREATE TABLE daily_chess_snapshots (local_day TEXT PRIMARY KEY, snapshot_version BIGINT NOT NULL, metrics_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', updated_at TEXT NOT NULL);
-- daily_queue_days
CREATE TABLE daily_queue_days (queue_date TEXT PRIMARY KEY, seed BIGINT NOT NULL, membership_hash TEXT NOT NULL, generated_at TEXT NOT NULL);
-- daily_statistics_jobs
CREATE TABLE daily_statistics_jobs (local_day TEXT PRIMARY KEY, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'complete', 'failed')), last_error TEXT, updated_at TEXT NOT NULL);
-- endgame_templates
CREATE TABLE endgame_templates (id TEXT PRIMARY KEY, card_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL, white_material TEXT NOT NULL, black_material TEXT NOT NULL, trained_color TEXT NOT NULL, goal_mix TEXT NOT NULL, enabled BIGINT NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
-- explorer_position_cache
CREATE TABLE explorer_position_cache (cache_key TEXT PRIMARY KEY, fen_key TEXT NOT NULL, speeds TEXT NOT NULL, ratings TEXT NOT NULL, response_json TEXT NOT NULL, fetched_at TEXT NOT NULL);
-- game_accounts
CREATE TABLE game_accounts (provider TEXT PRIMARY KEY, username TEXT NOT NULL, last_synced_at TEXT);
-- game_analysis_position_errors
CREATE TABLE game_analysis_position_errors (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, report_id TEXT NOT NULL, game_id TEXT NOT NULL, error TEXT NOT NULL, recorded_at TEXT NOT NULL);
-- game_insight_recommendations
CREATE TABLE game_insight_recommendations (motif TEXT PRIMARY KEY, miss_count BIGINT NOT NULL, total_loss_cp BIGINT NOT NULL, supporting_games_json TEXT NOT NULL, recommended_pack_id TEXT, updated_at TEXT NOT NULL);
-- game_sync_jobs
CREATE TABLE game_sync_jobs (id TEXT PRIMARY KEY, request_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'paused', 'retrying', 'complete', 'failed')), result_json TEXT, error TEXT, created_at TEXT NOT NULL, started_at TEXT, completed_at TEXT, updated_at TEXT NOT NULL);
-- game_sync_state
CREATE TABLE game_sync_state (provider TEXT PRIMARY KEY, status TEXT NOT NULL DEFAULT 'idle', cursor TEXT, last_started_at TEXT, last_success_at TEXT, last_error TEXT, retry_after TEXT, username TEXT NOT NULL DEFAULT '', last_result_json TEXT);
-- imported_games
CREATE TABLE imported_games (id TEXT PRIMARY KEY, provider TEXT NOT NULL, username TEXT NOT NULL, played_at TEXT NOT NULL, speed TEXT NOT NULL, rated BIGINT NOT NULL, color TEXT NOT NULL, result TEXT NOT NULL, start_fen TEXT NOT NULL, moves_json TEXT NOT NULL, game_url TEXT, opening_name TEXT, analysis_state TEXT NOT NULL DEFAULT 'pending', analysis_version BIGINT NOT NULL DEFAULT 0, major_mistake_ply BIGINT, missed_punishment_ply BIGINT, provider_game_id TEXT, content_hash TEXT, adaptive_excluded BIGINT NOT NULL DEFAULT 0, player_rating BIGINT, opponent_rating BIGINT, rating_change BIGINT, time_control TEXT, analysis_evidence_version BIGINT NOT NULL DEFAULT 1);
-- internal_migrations
CREATE TABLE internal_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
-- puzzle_decks
CREATE TABLE puzzle_decks (id TEXT PRIMARY KEY, name TEXT NOT NULL, themes_json TEXT NOT NULL, min_rating BIGINT NOT NULL, max_rating BIGINT NOT NULL, daily_limit BIGINT NOT NULL DEFAULT 5, created_at TEXT NOT NULL);
-- queue_projection_diagnostics
CREATE TABLE queue_projection_diagnostics (queue_date TEXT NOT NULL, card_id TEXT NOT NULL, message TEXT NOT NULL, PRIMARY KEY (queue_date, card_id));
-- queue_projections
CREATE TABLE queue_projections (queue_date TEXT PRIMARY KEY, state TEXT NOT NULL DEFAULT 'refreshing' CHECK (state IN ('ready', 'refreshing', 'failed')), generation BIGINT NOT NULL DEFAULT 0, updated_at TEXT, refresh_pending BIGINT NOT NULL DEFAULT 1, last_error TEXT, blocked_count BIGINT NOT NULL DEFAULT 0);
-- repertoire_integrity_source_runs
CREATE TABLE repertoire_integrity_source_runs (run_id TEXT NOT NULL, source_offset BIGINT NOT NULL, observations_json TEXT NOT NULL, invalid_json TEXT NOT NULL DEFAULT '[]', PRIMARY KEY (run_id, source_offset));
-- repertoires
CREATE TABLE repertoires (id TEXT PRIMARY KEY, name TEXT NOT NULL, source_name TEXT NOT NULL, created_at TEXT NOT NULL, is_main BIGINT NOT NULL DEFAULT 0);
-- settings
CREATE TABLE settings (id BIGINT PRIMARY KEY CHECK (id = 1), initial_depth BIGINT NOT NULL DEFAULT 6, timezone TEXT NOT NULL DEFAULT 'local', new_cards_per_day BIGINT NOT NULL DEFAULT 10, lichess_username TEXT NOT NULL DEFAULT '', chesscom_username TEXT NOT NULL DEFAULT '', auto_sync_minutes BIGINT NOT NULL DEFAULT 3, engine_line_window_cp BIGINT NOT NULL DEFAULT 30, major_mistake_cp BIGINT NOT NULL DEFAULT 100, light_first_interval_days BIGINT NOT NULL DEFAULT 7, draw_hold_user_moves BIGINT NOT NULL DEFAULT 20, tactics_new_per_day BIGINT NOT NULL DEFAULT 5, coverage_reply_denominator BIGINT NOT NULL DEFAULT 100, coverage_cumulative_target BIGINT NOT NULL DEFAULT 95, coverage_horizon_fullmoves BIGINT NOT NULL DEFAULT 15, coverage_path_floor DOUBLE PRECISION NOT NULL DEFAULT 0.0005, coverage_maia_elo BIGINT NOT NULL DEFAULT 1500, defense_new_cards_per_day BIGINT NOT NULL DEFAULT 5, discovery_window_days BIGINT NOT NULL DEFAULT 90, include_defensive_cards_in_daily_stack BIGINT NOT NULL DEFAULT 1, study_new_per_day BIGINT NOT NULL DEFAULT 2);
-- studies
CREATE TABLE studies (id TEXT PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', source_json TEXT NOT NULL DEFAULT '{}', archived BIGINT NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- tablebase_cache
CREATE TABLE tablebase_cache (fen_key TEXT PRIMARY KEY, response_json TEXT NOT NULL, fetched_at TEXT NOT NULL);
-- tactic_discovery_attempts
CREATE TABLE tactic_discovery_attempts (id TEXT PRIMARY KEY, deck_id TEXT NOT NULL, puzzle_id TEXT NOT NULL, clean BIGINT NOT NULL, result_json TEXT NOT NULL);
-- tactic_introductions
CREATE TABLE tactic_introductions (puzzle_id TEXT PRIMARY KEY, pack_id TEXT NOT NULL, introduction_date TEXT NOT NULL);
-- tactic_pack_activation
CREATE TABLE tactic_pack_activation (pack_id TEXT PRIMARY KEY, active BIGINT NOT NULL DEFAULT 0 CHECK (active IN (0, 1)));
-- tactic_progress
CREATE TABLE tactic_progress (puzzle_id TEXT PRIMARY KEY, deck_id TEXT NOT NULL, card_id TEXT, clean_pass_at TEXT, admitted_at TEXT, admission_mode TEXT NOT NULL DEFAULT 'light');
-- tactic_rotation
CREATE TABLE tactic_rotation (id BIGINT PRIMARY KEY CHECK (id = 1), last_pack_id TEXT NOT NULL DEFAULT '');
-- threat_analysis_report_history
CREATE TABLE threat_analysis_report_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, request_id TEXT NOT NULL, report_json TEXT NOT NULL, rejection_reason TEXT NOT NULL, archived_at TEXT NOT NULL);
-- threat_analysis_requests
CREATE TABLE threat_analysis_requests (id TEXT PRIMARY KEY, request_json TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'leased', 'complete', 'failed')), report_json TEXT, lease_id TEXT, lease_expires_at TEXT, attempts BIGINT NOT NULL DEFAULT 0, last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- background_task_events
CREATE TABLE background_task_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, task_id TEXT NOT NULL REFERENCES background_tasks (id) ON DELETE CASCADE, generation BIGINT NOT NULL, event TEXT NOT NULL, phase TEXT, detail TEXT, created_at TEXT NOT NULL);
-- endgame_attempts
CREATE TABLE endgame_attempts (id TEXT PRIMARY KEY, template_id TEXT NOT NULL REFERENCES endgame_templates (id) ON DELETE CASCADE, start_fen TEXT NOT NULL, target TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', user_moves BIGINT NOT NULL DEFAULT 0, created_at TEXT NOT NULL, completed_at TEXT);
-- game_analysis_jobs
CREATE TABLE game_analysis_jobs (game_id TEXT PRIMARY KEY REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'leased', 'complete', 'failed')), lease_id TEXT, lease_expires_at TEXT, idempotency_key TEXT, attempts BIGINT NOT NULL DEFAULT 0, last_error TEXT, updated_at TEXT NOT NULL, analysis_evidence_version BIGINT NOT NULL DEFAULT 1);
-- game_analysis_position_reports
CREATE TABLE game_analysis_position_reports (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, scan_pass TEXT NOT NULL CHECK (scan_pass IN ('shallow', 'confirmed')), position_index BIGINT NOT NULL, request_json TEXT NOT NULL, report_json TEXT, state TEXT NOT NULL CHECK (state IN ('leased', 'complete', 'queued', 'failed')), lease_id TEXT, parent_lease_id TEXT, lease_expires_at TEXT, attempts BIGINT NOT NULL DEFAULT 0, last_error TEXT, updated_at TEXT NOT NULL, UNIQUE (game_id, analysis_version, scan_pass, position_index));
-- game_derivation_jobs
CREATE TABLE game_derivation_jobs (game_id TEXT PRIMARY KEY REFERENCES imported_games (id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'complete', 'failed')), attempts BIGINT NOT NULL DEFAULT 0, last_error TEXT, updated_at TEXT NOT NULL, derivation_version BIGINT NOT NULL DEFAULT 1, next_attempt_at TEXT, phase TEXT, completed_phases BIGINT NOT NULL DEFAULT 0);
-- game_feature_rows
CREATE TABLE game_feature_rows (game_id TEXT PRIMARY KEY REFERENCES imported_games (id) ON DELETE CASCADE, feature_version BIGINT NOT NULL, local_day TEXT NOT NULL, local_hour BIGINT NOT NULL, local_weekday BIGINT NOT NULL, outcome_score DOUBLE PRECISION NOT NULL, player_decisions BIGINT NOT NULL, mean_loss_cp DOUBLE PRECISION, major_mistakes BIGINT, opening_exit_ply BIGINT, opening_exit_eval_cp BIGINT, endgame_entry_ply BIGINT, endgame_entry_eval_cp BIGINT, tactical_opportunities BIGINT NOT NULL DEFAULT 0, tactical_found BIGINT NOT NULL DEFAULT 0, tactical_conceded BIGINT NOT NULL DEFAULT 0, primary_repertoire_id TEXT, updated_at TEXT NOT NULL);
-- game_findings
CREATE TABLE game_findings (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, ply BIGINT NOT NULL, kind TEXT NOT NULL, confidence DOUBLE PRECISION NOT NULL, evidence_json TEXT NOT NULL, repertoire_id TEXT, card_id TEXT, motif TEXT, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'ignored', 'excluded')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, source_opportunity_id TEXT, review_after TEXT);
-- game_move_analysis
CREATE TABLE game_move_analysis (game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, ply BIGINT NOT NULL, eval_before_cp BIGINT, eval_after_cp BIGINT, loss_cp BIGINT, label TEXT, depth BIGINT NOT NULL, best_move_uci TEXT, principal_variation_json TEXT NOT NULL DEFAULT '[]', mate_before BIGINT, mate_after BIGINT, engine_version TEXT, network_version TEXT, mover_color TEXT, is_player_move BIGINT NOT NULL DEFAULT 1, actual_move_uci TEXT, position_fen TEXT, PRIMARY KEY (game_id, ply));
-- game_position_occurrences
CREATE TABLE game_position_occurrences (game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, ply BIGINT NOT NULL, fen_key TEXT NOT NULL, move_uci TEXT, PRIMARY KEY (game_id, ply));
-- game_repertoire_matches
CREATE TABLE game_repertoire_matches (game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, is_primary BIGINT NOT NULL DEFAULT 0, classification TEXT NOT NULL, matched_player_decisions BIGINT NOT NULL DEFAULT 0, repertoire_opportunities BIGINT NOT NULL DEFAULT 0, deepest_covered_ply BIGINT NOT NULL DEFAULT 0, first_player_deviation_ply BIGINT, first_player_deviation_fen TEXT, first_player_deviation_expected_json TEXT NOT NULL DEFAULT '[]', first_player_deviation_actual_uci TEXT, deviation_card_id TEXT, first_opponent_gap_ply BIGINT, out_of_book_ply BIGINT, timeline_json TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL, PRIMARY KEY (game_id, repertoire_id));
-- gameplay_events
CREATE TABLE gameplay_events (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, classifier_version BIGINT NOT NULL, ply BIGINT NOT NULL, kind TEXT NOT NULL, motif TEXT NOT NULL, beneficiary_color TEXT NOT NULL CHECK (beneficiary_color IN ('white', 'black')), created_by_color TEXT NOT NULL CHECK (created_by_color IN ('white', 'black')), outcome TEXT NOT NULL, confidence DOUBLE PRECISION NOT NULL, loss_cp BIGINT NOT NULL, best_move_uci TEXT, actual_move_uci TEXT, principal_variation_json TEXT NOT NULL DEFAULT '[]', evidence_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- guided_review_sessions
CREATE TABLE guided_review_sessions (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, finding_ids_json TEXT NOT NULL, current_index BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'complete')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- opening_graph_publications
CREATE TABLE opening_graph_publications (repertoire_id TEXT PRIMARY KEY REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL, state TEXT NOT NULL DEFAULT 'ready' CHECK (state IN ('ready', 'failed')), last_error TEXT, published_at TEXT NOT NULL);
-- position_annotations
CREATE TABLE position_annotations (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, fen_key TEXT NOT NULL, comment TEXT NOT NULL DEFAULT '', arrows_json TEXT NOT NULL DEFAULT '[]', squares_json TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL, PRIMARY KEY (repertoire_id, fen_key));
-- puzzles
CREATE TABLE puzzles (id TEXT PRIMARY KEY, deck_id TEXT NOT NULL REFERENCES puzzle_decks (id) ON DELETE CASCADE, source_fen TEXT NOT NULL, start_fen TEXT NOT NULL, moves_json TEXT NOT NULL, rating BIGINT NOT NULL, popularity BIGINT NOT NULL, themes_json TEXT NOT NULL, game_url TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'new' CHECK (state IN ('new', 'learning', 'mature')), due_date TEXT NOT NULL, interval_days BIGINT NOT NULL DEFAULT 0);
-- repertoire_comparisons
CREATE TABLE repertoire_comparisons (game_id TEXT PRIMARY KEY REFERENCES imported_games (id) ON DELETE CASCADE, repertoire_id TEXT, classification TEXT NOT NULL, divergence_ply BIGINT, divergence_fen TEXT, expected_json TEXT NOT NULL DEFAULT '[]', actual_uci TEXT, updated_at TEXT NOT NULL);
-- repertoire_coverage_runs
CREATE TABLE repertoire_coverage_runs (id TEXT PRIMARY KEY, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'complete', 'failed')), settings_json TEXT NOT NULL, total_nodes BIGINT NOT NULL DEFAULT 0, completed_nodes BIGINT NOT NULL DEFAULT 0, last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- repertoire_decision_gameplay_summaries
CREATE TABLE repertoire_decision_gameplay_summaries (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, fen_key TEXT NOT NULL, expected_uci TEXT NOT NULL, encounter_count BIGINT NOT NULL, success_count BIGINT NOT NULL, miss_count BIGINT NOT NULL, recent_encounter_count BIGINT NOT NULL, recent_success_count BIGINT NOT NULL, recent_miss_count BIGINT NOT NULL, last_encountered TEXT, route_success_count BIGINT, updated_at TEXT NOT NULL, PRIMARY KEY (repertoire_id, fen_key, expected_uci));
-- repertoire_integrity_issues
CREATE TABLE repertoire_integrity_issues (id TEXT PRIMARY KEY, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK (kind IN ('missing_response', 'multiple_responses', 'invalid_source')), fen_key TEXT, fen TEXT, trained_color TEXT, signature TEXT NOT NULL, moves_json TEXT NOT NULL DEFAULT '[]', sources_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- repertoire_integrity_jobs
CREATE TABLE repertoire_integrity_jobs (repertoire_id TEXT PRIMARY KEY REFERENCES repertoires (id) ON DELETE CASCADE, run_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'finalizing', 'complete', 'failed')), source_offset BIGINT NOT NULL DEFAULT 0, total_sources BIGINT NOT NULL DEFAULT 0, attempts BIGINT NOT NULL DEFAULT 0, last_error TEXT, updated_at TEXT NOT NULL);
-- repertoire_integrity_state
CREATE TABLE repertoire_integrity_state (repertoire_id TEXT PRIMARY KEY REFERENCES repertoires (id) ON DELETE CASCADE, status TEXT NOT NULL DEFAULT 'unchecked' CHECK (status IN ('unchecked', 'clean', 'needs_repair')), checked_at TEXT, scan_status TEXT NOT NULL DEFAULT 'idle' CHECK (scan_status IN ('idle', 'queued', 'running', 'retrying', 'failed')), scan_generation TEXT, scan_completed_sources BIGINT NOT NULL DEFAULT 0, scan_total_sources BIGINT NOT NULL DEFAULT 0, scan_error TEXT);
-- repertoire_lines
CREATE TABLE repertoire_lines (id TEXT PRIMARY KEY, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, name TEXT NOT NULL, trained_color TEXT NOT NULL, start_fen TEXT NOT NULL, moves_json TEXT NOT NULL, created_at TEXT NOT NULL);
-- repertoire_priority_jobs
CREATE TABLE repertoire_priority_jobs (repertoire_id TEXT PRIMARY KEY REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'complete', 'failed')), attempts BIGINT NOT NULL DEFAULT 0, next_attempt_at TEXT NOT NULL, last_error TEXT, updated_at TEXT NOT NULL);
-- repertoire_priority_publications
CREATE TABLE repertoire_priority_publications (repertoire_id TEXT PRIMARY KEY REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL, updated_at TEXT NOT NULL);
-- study_chapters
CREATE TABLE study_chapters (id TEXT PRIMARY KEY, study_id TEXT NOT NULL REFERENCES studies (id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', position BIGINT NOT NULL, archived BIGINT NOT NULL DEFAULT 0, UNIQUE (study_id, position));
-- tactical_opportunities
CREATE TABLE tactical_opportunities (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, ply BIGINT NOT NULL, motif TEXT NOT NULL, outcome TEXT NOT NULL CHECK (outcome IN ('exploited', 'missed')), confidence DOUBLE PRECISION NOT NULL, opportunity_value_cp BIGINT NOT NULL, evaluation_loss_cp BIGINT NOT NULL, played_move_uci TEXT NOT NULL, accepted_moves_json TEXT NOT NULL DEFAULT '[]', evidence_json TEXT NOT NULL, engine_version TEXT, network_version TEXT, active BIGINT NOT NULL DEFAULT 1 CHECK (active IN (0, 1)), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, superseded_at TEXT, UNIQUE (game_id, analysis_version, ply, motif));
-- game_move_analysis_candidates
CREATE TABLE game_move_analysis_candidates (game_id TEXT NOT NULL, ply BIGINT NOT NULL, rank BIGINT NOT NULL CHECK (rank >= 1), candidate_uci TEXT NOT NULL, score_cp BIGINT, mate BIGINT, score_text TEXT, principal_variation_json TEXT NOT NULL DEFAULT '[]', depth BIGINT NOT NULL, position_fen TEXT NOT NULL, engine_version TEXT NOT NULL, network_version TEXT NOT NULL, PRIMARY KEY (game_id, ply, rank), FOREIGN KEY (game_id, ply) REFERENCES game_move_analysis (game_id, ply) ON DELETE CASCADE);
-- guided_review_attempts
CREATE TABLE guided_review_attempts (session_id TEXT NOT NULL REFERENCES guided_review_sessions (id) ON DELETE CASCADE, finding_id TEXT NOT NULL REFERENCES game_findings (id) ON DELETE CASCADE, move_uci TEXT NOT NULL, correct BIGINT NOT NULL, attempted_at TEXT NOT NULL, PRIMARY KEY (session_id, finding_id));
-- opening_graph_steps
CREATE TABLE opening_graph_steps (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL, line_id TEXT NOT NULL REFERENCES repertoire_lines (id) ON DELETE CASCADE, decision_index BIGINT NOT NULL, card_id TEXT NOT NULL, parent_card_id TEXT, decision_fen_key TEXT NOT NULL, starting_fen TEXT NOT NULL, moves_json TEXT NOT NULL, trained_color TEXT NOT NULL CHECK (trained_color IN ('white', 'black')), segment_kind TEXT NOT NULL DEFAULT 'decision', first_decision_index BIGINT NOT NULL DEFAULT 0, last_decision_index BIGINT NOT NULL DEFAULT 0, decision_fen_keys_json TEXT NOT NULL DEFAULT '[]', PRIMARY KEY (repertoire_id, generation, line_id, decision_index));
-- repertoire_coverage_nodes
CREATE TABLE repertoire_coverage_nodes (id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES repertoire_coverage_runs (id) ON DELETE CASCADE, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, fen TEXT NOT NULL, fen_key TEXT NOT NULL, ply BIGINT NOT NULL, trained_color TEXT NOT NULL, routes_json TEXT NOT NULL, covered_replies_json TEXT NOT NULL, explorer_status TEXT NOT NULL DEFAULT 'queued', maia_status TEXT NOT NULL DEFAULT 'queued', explorer_games BIGINT NOT NULL DEFAULT 0, lease_id TEXT, lease_expires_at TEXT, last_error TEXT, updated_at TEXT NOT NULL, UNIQUE (run_id, fen_key));
-- repertoire_line_training_depths
CREATE TABLE repertoire_line_training_depths (line_id TEXT PRIMARY KEY REFERENCES repertoire_lines (id) ON DELETE CASCADE, learner_decision_count BIGINT NOT NULL CHECK (learner_decision_count >= 0));
-- study_sources
CREATE TABLE study_sources (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES study_chapters (id), source_group_id TEXT NOT NULL, version BIGINT NOT NULL, raw_pgn TEXT NOT NULL, sha256 TEXT NOT NULL, filename TEXT NOT NULL, record_index BIGINT NOT NULL, headers_json TEXT NOT NULL, diagnostics_json TEXT NOT NULL, valid BIGINT NOT NULL, created_at TEXT NOT NULL, UNIQUE (chapter_id, source_group_id, version, record_index));
-- repertoire_coverage_candidates
CREATE TABLE repertoire_coverage_candidates (node_id TEXT NOT NULL REFERENCES repertoire_coverage_nodes (id) ON DELETE CASCADE, move_uci TEXT NOT NULL, explorer_probability DOUBLE PRECISION, maia_probability DOUBLE PRECISION, blended_probability DOUBLE PRECISION, required BIGINT NOT NULL DEFAULT 0, covered BIGINT NOT NULL DEFAULT 0, source_state TEXT NOT NULL, PRIMARY KEY (node_id, move_uci));
-- study_positions
CREATE TABLE study_positions (id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES study_sources (id), parent_id TEXT REFERENCES study_positions (id), child_index BIGINT NOT NULL, move_uci TEXT, fen TEXT NOT NULL, history_json TEXT NOT NULL, comment TEXT NOT NULL DEFAULT '', starting_comment TEXT NOT NULL DEFAULT '', nags_json TEXT NOT NULL DEFAULT '[]', arrows_json TEXT NOT NULL DEFAULT '[]', squares_json TEXT NOT NULL DEFAULT '[]', node_path TEXT NOT NULL, valid BIGINT NOT NULL DEFAULT 1, UNIQUE (source_id, node_path));
-- study_exercises
CREATE TABLE study_exercises (id TEXT PRIMARY KEY, study_id TEXT NOT NULL REFERENCES studies (id), position_id TEXT NOT NULL REFERENCES study_positions (id), current_revision BIGINT NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')), sibling_group TEXT, source_json TEXT NOT NULL DEFAULT '{}', point_value DOUBLE PRECISION, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- cards
CREATE TABLE "cards" (id TEXT PRIMARY KEY, repertoire_id TEXT REFERENCES repertoires (id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK (kind IN ('prefix', 'response', 'checkpoint', 'exercise')), start_fen TEXT NOT NULL, moves_json TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'new' CHECK (state IN ('locked', 'new', 'learning', 'mature')), due_date TEXT NOT NULL, interval_days BIGINT NOT NULL DEFAULT 0, ease DOUBLE PRECISION NOT NULL DEFAULT 2.5, repetitions BIGINT NOT NULL DEFAULT 0, lapses BIGINT NOT NULL DEFAULT 0, unlock_after_card_id TEXT REFERENCES cards (id) ON DELETE SET NULL, fsrs_card_json TEXT, first_correct_at TEXT, reinforcement_pending BIGINT NOT NULL DEFAULT 0, stability DOUBLE PRECISION NOT NULL DEFAULT 0, guided_review BIGINT NOT NULL DEFAULT 0, maximum_interval BIGINT NOT NULL DEFAULT 365, content_type TEXT NOT NULL DEFAULT 'opening', scheduling_mode TEXT NOT NULL DEFAULT 'normal', hard_correct_streak BIGINT NOT NULL DEFAULT 0, recent_attempts_json TEXT NOT NULL DEFAULT '[]', archived BIGINT NOT NULL DEFAULT 0, superseded_by TEXT, source_ref TEXT, source_fen TEXT, revision BIGINT NOT NULL DEFAULT 1, introduced_at TEXT, trained_color TEXT, pending_validation BIGINT NOT NULL DEFAULT 0, prefix_split_rejected_after_review_id BIGINT NOT NULL DEFAULT -1, study_exercise_id TEXT REFERENCES study_exercises (id), CHECK ((study_exercise_id IS NULL AND NOT repertoire_id IS NULL) OR (NOT study_exercise_id IS NULL AND repertoire_id IS NULL AND content_type = 'study_exercise' AND kind = 'exercise')));
-- study_exercise_revisions
CREATE TABLE study_exercise_revisions (exercise_id TEXT NOT NULL REFERENCES study_exercises (id), revision BIGINT NOT NULL, specification_json TEXT NOT NULL, specification_hash TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (exercise_id, revision));
-- study_links
CREATE TABLE study_links (id TEXT PRIMARY KEY, study_id TEXT NOT NULL REFERENCES studies (id), source_position_id TEXT NOT NULL REFERENCES study_positions (id), target_position_id TEXT REFERENCES study_positions (id), target_exercise_id TEXT REFERENCES study_exercises (id), relation TEXT NOT NULL CHECK (relation IN ('illustrates', 'contrasts', 'follow_up')), CHECK ((target_position_id IS NULL) <> (target_exercise_id IS NULL)));
-- study_sibling_burials
CREATE TABLE study_sibling_burials (exercise_id TEXT NOT NULL REFERENCES study_exercises (id), study_day TEXT NOT NULL, reason TEXT NOT NULL, PRIMARY KEY (exercise_id, study_day));
-- daily_queue
CREATE TABLE daily_queue (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, queue_date TEXT NOT NULL, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, cycle BIGINT NOT NULL DEFAULT 0, position BIGINT NOT NULL, status TEXT NOT NULL DEFAULT 'queued', attempt_state TEXT NOT NULL DEFAULT 'clean', review_result_json TEXT, attempt_failed BIGINT NOT NULL DEFAULT 0, card_bucket TEXT, admission_kind TEXT, gameplay_priority_reason TEXT, admission_repertoire_id TEXT, admission_source TEXT, UNIQUE (queue_date, card_id, cycle));
-- gameplay_card_priorities
CREATE TABLE gameplay_card_priorities (card_id TEXT PRIMARY KEY REFERENCES cards (id) ON DELETE CASCADE, source_game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, finding_id TEXT NOT NULL, priority_date TEXT NOT NULL, reason TEXT NOT NULL, created_at TEXT NOT NULL);
-- opening_card_schedule_seeds
CREATE TABLE opening_card_schedule_seeds (card_id TEXT PRIMARY KEY REFERENCES cards (id) ON DELETE CASCADE, source_card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, baseline_successful_days BIGINT NOT NULL DEFAULT 0, baseline_recent_clean BIGINT NOT NULL DEFAULT 0, verification_due TEXT NOT NULL, created_at TEXT NOT NULL);
-- opening_graph_legacy_mappings
CREATE TABLE opening_graph_legacy_mappings (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL, legacy_card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, decision_card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, PRIMARY KEY (repertoire_id, generation, legacy_card_id, decision_card_id));
-- prefix_splits
CREATE TABLE prefix_splits (source_card_id TEXT PRIMARY KEY REFERENCES cards (id) ON DELETE CASCADE, source_revision BIGINT NOT NULL, shortened_card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, continuation_card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, created_at TEXT NOT NULL);
-- repertoire_card_introduction_priorities
CREATE TABLE repertoire_card_introduction_priorities (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, scoring_version BIGINT NOT NULL, completed_line_ids_json TEXT NOT NULL DEFAULT '[]', completion_mass DOUBLE PRECISION NOT NULL DEFAULT 0, frontier_decisions_json TEXT NOT NULL DEFAULT '[]', frontier_reach DOUBLE PRECISION NOT NULL DEFAULT 0, priority_score DOUBLE PRECISION NOT NULL DEFAULT 0, evidence_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL, PRIMARY KEY (repertoire_id, card_id));
-- repertoire_card_priority_generations
CREATE TABLE repertoire_card_priority_generations (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, generation BIGINT NOT NULL, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, scoring_version BIGINT NOT NULL, completed_line_ids_json TEXT NOT NULL DEFAULT '[]', completion_mass DOUBLE PRECISION NOT NULL DEFAULT 0, frontier_decisions_json TEXT NOT NULL DEFAULT '[]', frontier_reach DOUBLE PRECISION NOT NULL DEFAULT 0, priority_score DOUBLE PRECISION NOT NULL DEFAULT 0, evidence_json TEXT NOT NULL DEFAULT '{}', updated_at TEXT NOT NULL, PRIMARY KEY (repertoire_id, generation, card_id));
-- repertoire_cards
CREATE TABLE repertoire_cards (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, PRIMARY KEY (repertoire_id, card_id));
-- repertoire_decision_events
CREATE TABLE repertoire_decision_events (id TEXT PRIMARY KEY, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, card_id TEXT REFERENCES cards (id) ON DELETE SET NULL, ply BIGINT NOT NULL, fen_key TEXT NOT NULL, expected_uci TEXT NOT NULL, actual_uci TEXT NOT NULL, outcome TEXT NOT NULL CHECK (outcome IN ('miss', 'success')), played_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE (game_id, repertoire_id, ply));
-- repertoire_integrity_card_blocks
CREATE TABLE repertoire_integrity_card_blocks (repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, issue_id TEXT NOT NULL REFERENCES repertoire_integrity_issues (id) ON DELETE CASCADE, scan_generation TEXT NOT NULL, published_at TEXT NOT NULL, PRIMARY KEY (repertoire_id, card_id, issue_id));
-- repertoire_opportunities
CREATE TABLE repertoire_opportunities (id TEXT PRIMARY KEY, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, kind TEXT NOT NULL CHECK (kind IN ('weak_known_decision', 'missing_response', 'post_gap_weakness')), fen_key TEXT NOT NULL, card_id TEXT REFERENCES cards (id) ON DELETE SET NULL, opponent_move_uci TEXT, status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'dismissed', 'resolved')), score DOUBLE PRECISION NOT NULL, evidence_json TEXT NOT NULL, evidence_fingerprint TEXT NOT NULL, dismissed_evidence_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, resolved_at TEXT, seen_at TEXT, snoozed_until TEXT, admission_state TEXT, admitted_card_id TEXT);
-- reviews
CREATE TABLE reviews (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, rating TEXT NOT NULL, reviewed_at TEXT NOT NULL, previous_interval BIGINT NOT NULL, next_interval BIGINT NOT NULL, internal_rating TEXT NOT NULL DEFAULT 'again', guided BIGINT NOT NULL DEFAULT 0, source_kind TEXT NOT NULL DEFAULT 'study', source_ref TEXT, invalidated_at TEXT, invalidation_reason TEXT);
-- teaching_states
CREATE TABLE teaching_states (card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, revision BIGINT NOT NULL, ply BIGINT NOT NULL, taught_at TEXT NOT NULL, PRIMARY KEY (card_id, revision, ply));
-- threat_training_candidates
CREATE TABLE threat_training_candidates (id TEXT PRIMARY KEY, finding_id TEXT NOT NULL REFERENCES game_findings (id) ON DELETE CASCADE, game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, analysis_version BIGINT NOT NULL, incident_id TEXT NOT NULL, player_ply BIGINT NOT NULL, validation_state TEXT NOT NULL DEFAULT 'needs_analysis', diagnostic TEXT NOT NULL DEFAULT '', evidence_json TEXT NOT NULL, validation_json TEXT NOT NULL DEFAULT '{}', source_fingerprint TEXT NOT NULL, detector_version BIGINT NOT NULL, policy_json TEXT NOT NULL, exercise_revision BIGINT NOT NULL DEFAULT 1, dismissed_at TEXT, dismissed_evidence_fingerprint TEXT, approved_at TEXT, card_id TEXT REFERENCES cards (id) ON DELETE SET NULL, superseded_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, paused_at TEXT, admission_mode TEXT, UNIQUE (game_id, analysis_version, incident_id, player_ply));
-- coverage_discovery_recommendation_requests
CREATE TABLE coverage_discovery_recommendation_requests (opportunity_id TEXT PRIMARY KEY REFERENCES repertoire_opportunities (id) ON DELETE CASCADE, request_id TEXT NOT NULL REFERENCES threat_analysis_requests (id) ON DELETE CASCADE, coverage_node_id TEXT NOT NULL REFERENCES repertoire_coverage_nodes (id) ON DELETE CASCADE, route_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- defense_attempts
CREATE TABLE defense_attempts (attempt_id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL REFERENCES threat_training_candidates (id) ON DELETE CASCADE, card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE, queue_entry_id BIGINT, exercise_revision BIGINT NOT NULL, move_uci TEXT NOT NULL, grade_json TEXT NOT NULL, reviewed_at TEXT NOT NULL);
-- defense_recognition_submissions
CREATE TABLE defense_recognition_submissions (attempt_id TEXT PRIMARY KEY, candidate_id TEXT NOT NULL REFERENCES threat_training_candidates (id) ON DELETE CASCADE, queue_entry_id BIGINT NOT NULL REFERENCES daily_queue (id) ON DELETE CASCADE, exercise_revision BIGINT NOT NULL, answer_json TEXT NOT NULL, recognition_correct BIGINT NOT NULL, created_at TEXT NOT NULL);
-- discovery_admission_intents
CREATE TABLE discovery_admission_intents (id TEXT PRIMARY KEY, opportunity_id TEXT NOT NULL REFERENCES repertoire_opportunities (id) ON DELETE CASCADE, repertoire_id TEXT NOT NULL REFERENCES repertoires (id) ON DELETE CASCADE, evidence_fingerprint TEXT NOT NULL, starting_fen TEXT NOT NULL, selected_move_uci TEXT NOT NULL, preview_moves_json TEXT NOT NULL, recommendation_json TEXT NOT NULL, line_id TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'preparing', card_id TEXT, last_error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE (opportunity_id, selected_move_uci));
-- discovery_recommendation_requests
CREATE TABLE discovery_recommendation_requests (opportunity_id TEXT PRIMARY KEY REFERENCES repertoire_opportunities (id) ON DELETE CASCADE, request_id TEXT NOT NULL REFERENCES threat_analysis_requests (id) ON DELETE CASCADE, source_game_id TEXT NOT NULL REFERENCES imported_games (id) ON DELETE CASCADE, source_ply BIGINT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
-- study_attempts
CREATE TABLE study_attempts (id TEXT PRIMARY KEY, exercise_id TEXT NOT NULL REFERENCES study_exercises (id), revision BIGINT NOT NULL, card_id TEXT REFERENCES cards (id), queue_entry_id BIGINT REFERENCES daily_queue (id), cycle BIGINT, context TEXT NOT NULL CHECK (context IN ('practice', 'review')), answer_json TEXT NOT NULL, answer_hash TEXT NOT NULL, assessment_json TEXT NOT NULL, assessment_method TEXT NOT NULL, grader_version BIGINT NOT NULL, hint_seen BIGINT NOT NULL DEFAULT 0, solution_seen_before_answer BIGINT NOT NULL DEFAULT 0, started_at TEXT NOT NULL, committed_at TEXT NOT NULL, finalized_at TEXT, result_json TEXT, UNIQUE (queue_entry_id));
-- threat_candidate_requests
CREATE TABLE threat_candidate_requests (candidate_id TEXT NOT NULL REFERENCES threat_training_candidates (id) ON DELETE CASCADE, request_id TEXT NOT NULL REFERENCES threat_analysis_requests (id) ON DELETE CASCADE, role TEXT NOT NULL CHECK (role IN ('best', 'historical', 'attempt')), PRIMARY KEY (candidate_id, request_id, role));
-- SQLite JSON and date functions used by existing domain queries.
CREATE FUNCTION json_extract_path_text(document TEXT, VARIADIC path TEXT[]) RETURNS TEXT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT jsonb_extract_path_text(document::jsonb, VARIADIC path) $$;
CREATE FUNCTION json_each(document TEXT) RETURNS TABLE(key TEXT, value TEXT) LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT (ordinality - 1)::text, element::text FROM jsonb_array_elements(CASE WHEN jsonb_typeof(document::jsonb) = 'array' THEN document::jsonb ELSE '[]'::jsonb END) WITH ORDINALITY AS items(element, ordinality) UNION ALL SELECT object_key, element::text FROM jsonb_each(CASE WHEN jsonb_typeof(document::jsonb) = 'object' THEN document::jsonb ELSE '{}'::jsonb END) AS items(object_key, element) $$;
CREATE FUNCTION json_array_length(document TEXT) RETURNS BIGINT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT CASE WHEN jsonb_typeof(document::jsonb) = 'array' THEN jsonb_array_length(document::jsonb) ELSE 0 END $$;
CREATE FUNCTION julianday(moment TEXT) RETURNS DOUBLE PRECISION LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT EXTRACT(EPOCH FROM moment::timestamptz) / 86400.0 + 2440587.5 $$;
CREATE FUNCTION datetime(moment TEXT, modifier TEXT) RETURNS TEXT LANGUAGE SQL VOLATILE AS $$ SELECT CASE WHEN moment = 'now' AND modifier = '-1 day' THEN to_char(clock_timestamp() - interval '1 day', 'YYYY-MM-DD HH24:MI:SS') ELSE NULL END $$;
CREATE FUNCTION last_insert_rowid() RETURNS BIGINT LANGUAGE SQL VOLATILE AS $$ SELECT lastval() $$;
-- idx_background_task_events_task
CREATE INDEX idx_background_task_events_task ON background_task_events(task_id NULLS FIRST, id DESC NULLS LAST);
-- idx_background_tasks_claim
CREATE INDEX idx_background_tasks_claim ON background_tasks(state NULLS FIRST, priority NULLS FIRST, next_attempt_at NULLS FIRST, created_at NULLS FIRST);
-- idx_cards_due_state
CREATE INDEX idx_cards_due_state ON cards(due_date NULLS FIRST, state NULLS FIRST);
-- idx_coverage_discovery_recommendation_request
CREATE INDEX idx_coverage_discovery_recommendation_request ON coverage_discovery_recommendation_requests(request_id NULLS FIRST);
-- idx_coverage_nodes_work
CREATE INDEX idx_coverage_nodes_work ON repertoire_coverage_nodes(explorer_status NULLS FIRST, maia_status NULLS FIRST, updated_at NULLS FIRST);
-- idx_coverage_runs_repertoire
CREATE INDEX idx_coverage_runs_repertoire ON repertoire_coverage_runs(repertoire_id NULLS FIRST, created_at NULLS FIRST);
-- idx_daily_queue_order
CREATE INDEX idx_daily_queue_order ON daily_queue(queue_date NULLS FIRST, status NULLS FIRST, position NULLS FIRST);
-- idx_discovery_recommendation_request
CREATE INDEX idx_discovery_recommendation_request ON discovery_recommendation_requests(request_id NULLS FIRST);
-- idx_game_analysis_candidates_move
CREATE INDEX idx_game_analysis_candidates_move ON game_move_analysis_candidates(game_id NULLS FIRST, ply NULLS FIRST, candidate_uci NULLS FIRST);
-- idx_game_analysis_jobs_status
CREATE INDEX idx_game_analysis_jobs_status ON game_analysis_jobs(status NULLS FIRST, updated_at NULLS FIRST);
-- idx_game_analysis_positions_state
CREATE INDEX idx_game_analysis_positions_state ON game_analysis_position_reports(game_id NULLS FIRST, analysis_version NULLS FIRST, state NULLS FIRST);
-- idx_game_derivation_jobs_status
CREATE INDEX idx_game_derivation_jobs_status ON game_derivation_jobs(status NULLS FIRST, updated_at NULLS FIRST);
-- idx_game_features_day
CREATE INDEX idx_game_features_day ON game_feature_rows(local_day NULLS FIRST, game_id NULLS FIRST);
-- idx_game_findings_opportunity
CREATE INDEX idx_game_findings_opportunity ON game_findings(source_opportunity_id NULLS FIRST);
-- idx_game_findings_repertoire_gap
CREATE INDEX idx_game_findings_repertoire_gap ON game_findings(repertoire_id NULLS FIRST, kind NULLS FIRST, JSON_EXTRACT_PATH_TEXT(evidence_json, 'opponent_gap_fen_key') NULLS FIRST, JSON_EXTRACT_PATH_TEXT(evidence_json, 'opponent_gap_move_uci') NULLS FIRST);
-- idx_game_findings_status
CREATE INDEX idx_game_findings_status ON game_findings(status NULLS FIRST, kind NULLS FIRST, updated_at NULLS FIRST);
-- idx_game_positions_fen
CREATE INDEX idx_game_positions_fen ON game_position_occurrences(fen_key NULLS FIRST, game_id NULLS FIRST);
-- idx_game_repertoire_matches_primary
CREATE INDEX idx_game_repertoire_matches_primary ON game_repertoire_matches(game_id NULLS FIRST, is_primary NULLS FIRST);
-- idx_game_sync_jobs_status
CREATE INDEX idx_game_sync_jobs_status ON game_sync_jobs(status NULLS FIRST, created_at NULLS FIRST);
-- idx_gameplay_events_game_ply
CREATE INDEX idx_gameplay_events_game_ply ON gameplay_events(game_id NULLS FIRST, ply NULLS FIRST, kind NULLS FIRST);
-- idx_gameplay_events_motif
CREATE INDEX idx_gameplay_events_motif ON gameplay_events(motif NULLS FIRST, outcome NULLS FIRST, confidence NULLS FIRST);
-- idx_gameplay_priorities_date
CREATE INDEX idx_gameplay_priorities_date ON gameplay_card_priorities(priority_date NULLS FIRST, card_id NULLS FIRST);
-- idx_guided_review_game
CREATE INDEX idx_guided_review_game ON guided_review_sessions(game_id NULLS FIRST, status NULLS FIRST, updated_at NULLS FIRST);
-- idx_imported_games_account_date
CREATE INDEX idx_imported_games_account_date ON imported_games(provider NULLS FIRST, username NULLS FIRST, played_at NULLS FIRST);
-- idx_imported_games_content_hash
CREATE INDEX idx_imported_games_content_hash ON imported_games(provider NULLS FIRST, username NULLS FIRST, content_hash NULLS FIRST) WHERE NOT content_hash IS NULL;
-- idx_imported_games_provider_game_id
CREATE UNIQUE INDEX idx_imported_games_provider_game_id ON imported_games(provider NULLS FIRST, provider_game_id NULLS FIRST) WHERE NOT provider_game_id IS NULL;
-- idx_integrity_card_blocks_card
CREATE INDEX idx_integrity_card_blocks_card ON repertoire_integrity_card_blocks(card_id NULLS FIRST, repertoire_id NULLS FIRST);
-- idx_introduction_priorities_score
CREATE INDEX idx_introduction_priorities_score ON repertoire_card_introduction_priorities(repertoire_id NULLS FIRST, priority_score DESC NULLS LAST);
-- idx_opening_graph_steps_card
CREATE INDEX idx_opening_graph_steps_card ON opening_graph_steps(repertoire_id NULLS FIRST, generation NULLS FIRST, card_id NULLS FIRST);
-- idx_opening_graph_steps_parent
CREATE INDEX idx_opening_graph_steps_parent ON opening_graph_steps(repertoire_id NULLS FIRST, generation NULLS FIRST, parent_card_id NULLS FIRST);
-- idx_opening_graph_steps_queue_card
CREATE INDEX idx_opening_graph_steps_queue_card ON opening_graph_steps(card_id NULLS FIRST, repertoire_id NULLS FIRST, generation NULLS FIRST, parent_card_id NULLS FIRST);
-- idx_position_annotations_fen
CREATE INDEX idx_position_annotations_fen ON position_annotations(fen_key NULLS FIRST);
-- idx_priority_generation_score
CREATE INDEX idx_priority_generation_score ON repertoire_card_priority_generations(repertoire_id NULLS FIRST, generation NULLS FIRST, priority_score DESC NULLS LAST);
-- idx_puzzles_deck_due_state
CREATE INDEX idx_puzzles_deck_due_state ON puzzles(deck_id NULLS FIRST, due_date NULLS FIRST, state NULLS FIRST);
-- idx_repertoire_cards_card
CREATE INDEX idx_repertoire_cards_card ON repertoire_cards(card_id NULLS FIRST, repertoire_id NULLS FIRST);
-- idx_repertoire_decision_events_card_time
CREATE INDEX idx_repertoire_decision_events_card_time ON repertoire_decision_events(card_id NULLS FIRST, played_at NULLS FIRST, outcome NULLS FIRST);
-- idx_repertoire_decision_events_position
CREATE INDEX idx_repertoire_decision_events_position ON repertoire_decision_events(repertoire_id NULLS FIRST, fen_key NULLS FIRST, expected_uci NULLS FIRST, played_at NULLS FIRST);
-- idx_repertoire_integrity_jobs_status
CREATE INDEX idx_repertoire_integrity_jobs_status ON repertoire_integrity_jobs(status NULLS FIRST, updated_at NULLS FIRST);
-- idx_repertoire_integrity_repertoire
CREATE INDEX idx_repertoire_integrity_repertoire ON repertoire_integrity_issues(repertoire_id NULLS FIRST, updated_at NULLS FIRST, id NULLS FIRST);
-- idx_repertoire_integrity_state_status
CREATE INDEX idx_repertoire_integrity_state_status ON repertoire_integrity_state(status NULLS FIRST);
-- idx_repertoire_lines_repertoire_created
CREATE INDEX idx_repertoire_lines_repertoire_created ON repertoire_lines(repertoire_id NULLS FIRST, created_at NULLS FIRST, id NULLS FIRST);
-- idx_repertoire_opportunities_list
CREATE INDEX idx_repertoire_opportunities_list ON repertoire_opportunities(repertoire_id NULLS FIRST, status NULLS FIRST, score DESC NULLS LAST);
-- idx_repertoire_priority_jobs_status
CREATE INDEX idx_repertoire_priority_jobs_status ON repertoire_priority_jobs(status NULLS FIRST, next_attempt_at NULLS FIRST, updated_at NULLS FIRST);
-- idx_reviews_card_reviewed_at
CREATE INDEX idx_reviews_card_reviewed_at ON reviews(card_id NULLS FIRST, reviewed_at NULLS FIRST);
-- idx_reviews_source
CREATE UNIQUE INDEX idx_reviews_source ON reviews(source_kind NULLS FIRST, source_ref NULLS FIRST) WHERE NOT source_ref IS NULL;
-- idx_study_active_card
CREATE UNIQUE INDEX idx_study_active_card ON cards(study_exercise_id NULLS FIRST) WHERE NOT study_exercise_id IS NULL AND archived = 0;
-- idx_study_attempts_exercise
CREATE INDEX idx_study_attempts_exercise ON study_attempts(exercise_id NULLS FIRST, committed_at NULLS FIRST);
-- idx_study_chapters_study
CREATE INDEX idx_study_chapters_study ON study_chapters(study_id NULLS FIRST, position NULLS FIRST);
-- idx_study_exercises_position
CREATE INDEX idx_study_exercises_position ON study_exercises(position_id NULLS FIRST, status NULLS FIRST);
-- idx_study_positions_parent
CREATE INDEX idx_study_positions_parent ON study_positions(parent_id NULLS FIRST, child_index NULLS FIRST);
-- idx_study_sources_chapter
CREATE INDEX idx_study_sources_chapter ON study_sources(chapter_id NULLS FIRST, source_group_id NULLS FIRST, version NULLS FIRST);
-- idx_tactic_progress_deck_clean
CREATE INDEX idx_tactic_progress_deck_clean ON tactic_progress(deck_id NULLS FIRST, clean_pass_at NULLS FIRST);
-- idx_tactical_opportunities_game_version
CREATE INDEX idx_tactical_opportunities_game_version ON tactical_opportunities(game_id NULLS FIRST, analysis_version NULLS FIRST, ply NULLS FIRST, active NULLS FIRST);
-- idx_tactical_opportunities_motif_outcome
CREATE INDEX idx_tactical_opportunities_motif_outcome ON tactical_opportunities(motif NULLS FIRST, outcome NULLS FIRST, active NULLS FIRST);
-- idx_tactical_opportunities_updated
CREATE INDEX idx_tactical_opportunities_updated ON tactical_opportunities(updated_at NULLS FIRST, outcome NULLS FIRST);
-- idx_threat_analysis_requests_state
CREATE INDEX idx_threat_analysis_requests_state ON threat_analysis_requests(state NULLS FIRST, updated_at NULLS FIRST);
-- idx_threat_candidates_card_id
CREATE INDEX idx_threat_candidates_card_id ON threat_training_candidates(card_id NULLS FIRST);
-- idx_threat_candidates_game_state
CREATE INDEX idx_threat_candidates_game_state ON threat_training_candidates(game_id NULLS FIRST, validation_state NULLS FIRST, superseded_at NULLS FIRST);
CREATE TABLE tempo_migration_progress (table_name TEXT PRIMARY KEY, source_count BIGINT NOT NULL, source_sha256 TEXT NOT NULL, copied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE operation_receipts (operation_id TEXT PRIMARY KEY, command_name TEXT NOT NULL, request_hash TEXT NOT NULL, state TEXT NOT NULL CHECK (state IN ('pending','complete','failed')), response_json TEXT, error_json TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_operation_receipts_state_updated ON operation_receipts(state, updated_at);
INSERT INTO tempo_schema_migrations(version) VALUES (1);
