import { STANDARD_FEN } from "./const";
import type { EndgameMaterial } from "./lib/endgame-generator";
import {
  LocalRepertoire,
  PracticeCard,
  asCardId,
  asRepertoireId,
} from "./types";

export const analysisLines = [
  {
    title: "Open Sicilian · Najdorf",
    side: "White",
    moves: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"],
  },
  {
    title: "French · Classical",
    side: "White",
    moves: ["e4", "e6", "d4", "d5", "Nc3", "Nf6", "e5", "Nfd7"],
  },
  {
    title: "Caro-Kann · Advance",
    side: "White",
    moves: ["e4", "c6", "d4", "d5", "e5", "Bf5", "Nf3", "e6"],
  },
  {
    title: "King’s Indian · Main line",
    side: "Black",
    moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"],
  },
];

export const demoCards = [
  {
    id: asCardId("open-sicilian-prefix"),
    kind: "opening",
    title: "Open Sicilian",
    subtitle: "Najdorf setup",
    startingFen: STANDARD_FEN,
    moves: [
      "e4",
      "c5",
      "Nf3",
      "d6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "a6",
      "Be3",
    ],
    userMoveTarget: 6,
    nextMove: "… e6 · 7. Qd2",
  },
  {
    id: asCardId("french-classical-prefix"),
    kind: "opening",
    title: "French Defense",
    subtitle: "Classical variation",
    startingFen: STANDARD_FEN,
    moves: [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "e5",
      "Nfd7",
      "f4",
      "c5",
      "Nf3",
    ],
    userMoveTarget: 6,
    nextMove: "… Nc6 · 7. Be3",
  },
  {
    id: asCardId("lichess-puzzle-00sHx"),
    kind: "puzzle",
    title: "Mate in two",
    subtitle: "Mate · middlegame · short",
    startingFen: "q5nr/1ppknQpp/3p4/1P2p3/4P3/B1PP1b2/B5PP/5K2 w - - 1 18",
    moves: ["Be6+", "Kd8", "Qf8#"],
    userMoveTarget: 2,
    sourceUrl: "https://lichess.org/training/00sHx",
  },
] satisfies PracticeCard[];

export const bundledRepertoires: LocalRepertoire[] = [
  {
    id: asRepertoireId("sample-white"),
    title: "1. e4 Main Lines",
    sourceName: "Tempo examples",
    side: "white",
    pgn: '[Event "1. e4 Main Lines"]\n[Result "*"]\n\n1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. Be3 *',
    cards: demoCards.filter((card) => card.kind === "opening").map((card) => ({
      ...card,
      orientation: "white",
      repertoireId: asRepertoireId("sample-white"),
      revision: 1,
    })),
  },
  {
    id: asRepertoireId("sample-black"),
    title: "King’s Indian",
    sourceName: "Tempo examples",
    side: "black",
    pgn: '[Event "King’s Indian"]\n[Result "*"]\n\n1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6 *',
    cards: [
      {
        id: asCardId("sample-black-kid-prefix"),
        kind: "opening",
        title: "King’s Indian",
        subtitle: "Main line",
        startingFen: STANDARD_FEN,
        moves: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6"],
        userMoveTarget: 4,
        orientation: "black",
        repertoireId: asRepertoireId("sample-black"),
        revision: 1,
      },
    ],
  },
];

export const sampleGames = [
  {
    id: "g1",
    source: "Lichess",
    date: "Sep 12",
    speed: "Rapid",
    color: "White",
    result: "Won",
    opening: "Open Sicilian",
    status: "covered",
    detail: "Covered through 12… Be7",
    flag: "First major mistake · 18. Bxh7? · −1.24",
    flagPly: 13,
    moves: [
      "e4",
      "c5",
      "Nf3",
      "d6",
      "d4",
      "cxd4",
      "Nxd4",
      "Nf6",
      "Nc3",
      "a6",
      "Be3",
      "e6",
      "f3",
      "b5",
      "Qd2",
    ],
  },
  {
    id: "g2",
    source: "Chess.com",
    date: "Sep 10",
    speed: "Blitz",
    color: "Black",
    result: "Lost",
    opening: "King’s Indian",
    status: "opponent gap",
    detail: "New opponent move 7. d5",
    flag: "Missed punishment · 12… Nxe4 · +1.18 available",
    flagPly: 9,
    moves: [
      "d4",
      "Nf6",
      "c4",
      "g6",
      "Nc3",
      "Bg7",
      "e4",
      "d6",
      "Nf3",
      "O-O",
      "Be2",
    ],
  },
  {
    id: "g3",
    source: "Lichess",
    date: "Sep 8",
    speed: "Blitz",
    color: "White",
    result: "Draw",
    opening: "French Defense",
    status: "player deviation",
    detail: "You played 8. Bd3 instead of 8. Qd2",
    flag: "First major mistake · 8. Bd3 · −1.07",
    flagPly: 10,
    moves: [
      "e4",
      "e6",
      "d4",
      "d5",
      "Nc3",
      "Nf6",
      "e5",
      "Nfd7",
      "f4",
      "c5",
      "Nf3",
    ],
  },
  {
    id: "g4",
    source: "Lichess",
    date: "Sep 2",
    speed: "Classical",
    color: "Black",
    result: "Won",
    opening: "English Opening",
    status: "no repertoire",
    detail: "No applicable Black repertoire",
    flag: "No ≥100cp swing found",
    flagPly: 0,
    moves: ["c4", "e5", "Nc3", "Nf6", "g3", "d5"],
  },
];

export const tacticMotifs = [
  ["hangingPiece", "Hanging pieces", "♟"],
  ["fork", "Forks", "♘"],
  ["pin", "Pins", "⌖"],
  ["skewer", "Skewers", "⇥"],
  ["discoveredAttack", "Discoveries", "✦"],
  ["mateIn1", "Mate in 1", "#1"],
  ["mateIn2", "Mate in 2", "#2"],
  ["mateIn3", "Mate in 3", "#3"],
  ["mateIn4Plus", "Mate in 4+", "#4"],
  ["calculation2", "2-move calculation", "2×"],
  ["calculation3", "3-move calculation", "3×"],
  ["calculation4", "4-move calculation", "4×"],
  ["trappedPiece", "Trapped pieces", "▣"],
];
export const hangingSample: PracticeCard = {
  id: asCardId("hanging-sample"),
  kind: "puzzle",
  title: "Loose queen",
  subtitle: "Hanging piece",
  startingFen: "4k3/8/8/8/3q4/3R4/8/4K3 w - - 0 1",
  moves: ["Rxd4"],
  userMoveTarget: 1,
};
export const tacticExamples: Record<string, PracticeCard> = {
  hangingPiece: hangingSample,
  fork: {
    id: asCardId("fork-sample"),
    kind: "puzzle",
    title: "Knight fork",
    subtitle: "Fork",
    startingFen: "3q3k/8/8/4N3/8/8/8/4K3 w - - 0 1",
    moves: ["Nf7+"],
    userMoveTarget: 1,
  },
  pin: {
    id: asCardId("pin-sample"),
    kind: "puzzle",
    title: "Create the pin",
    subtitle: "Pin",
    startingFen: "4k3/8/2n5/8/2B5/8/8/4K3 w - - 0 1",
    moves: ["Bb5"],
    userMoveTarget: 1,
  },
  skewer: {
    id: asCardId("skewer-sample"),
    kind: "puzzle",
    title: "Skewer king and queen",
    subtitle: "Skewer",
    startingFen: "4k3/8/8/7q/8/8/2B5/4K3 w - - 0 1",
    moves: ["Bg6+"],
    userMoveTarget: 1,
  },
  discoveredAttack: {
    id: asCardId("discovery-sample"),
    kind: "puzzle",
    title: "Open the file",
    subtitle: "Discovery",
    startingFen: "4k3/8/8/8/4B3/8/8/4R1K1 w - - 0 1",
    moves: ["Bd5+"],
    userMoveTarget: 1,
  },
};
export const alternateTactics: PracticeCard[] = [
  {
    id: asCardId("loose-rook"),
    kind: "puzzle",
    title: "Loose rook",
    subtitle: "Material",
    startingFen: "4k3/8/5r2/8/8/2B5/8/4K3 w - - 0 1",
    moves: ["Bxf6"],
    userMoveTarget: 1,
  },
  {
    id: asCardId("loose-knight"),
    kind: "puzzle",
    title: "Loose knight",
    subtitle: "Material",
    startingFen: "4k3/8/8/3n4/8/8/8/3QK3 w - - 0 1",
    moves: ["Qxd5"],
    userMoveTarget: 1,
  },
  demoCards[2],
];
export const endgameTemplates: EndgameMaterial[] = [
  { white: "KQ", black: "K", name: "Queen + king" },
  { white: "KR", black: "K", name: "Rook + king" },
  { white: "KQR", black: "K", name: "Queen + rook" },
  { white: "KQQ", black: "K", name: "Two queens" },
];
