import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
const directory = mkdtempSync(join(tmpdir(), "tempo-browser-tests-"));
const python = existsSync(".venv/bin/python") ? ".venv/bin/python" : "python3";
const apiPort = process.env.TEMPO_BROWSER_API_PORT ?? "8001";
const api = spawn(python, ["-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", apiPort], { stdio: "inherit", env: { ...process.env, PYTHONPATH: "backend", TEMPO_TEST_INSTANCE: "disposable", TEMPO_DB_PATH: join(directory, "tempo.db") } });
const cleanup = () => { api.kill("SIGTERM"); };
process.on("SIGINT", cleanup);
process.on("SIGTERM", cleanup);
api.on("exit", (code) => { rmSync(directory, { recursive: true }); process.exit(code ?? 0); });
